apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
  namespace: afrank-dev
data:
  config.json: |
    {"THIS":"is a test","HERE": "is another test","KEY": "here's another key", "ANOTHER": "and yet another key"}
